import { useEffect, useState } from 'react'
import { Button, Form, Input, Select, Space, Switch, message } from 'antd'
import { MinusCircleOutlined, PlusOutlined } from '@ant-design/icons'
import { useNavigate, useSearchParams } from 'react-router-dom'
import HeadLable from '@/components/HeadLable';import ImgUpload from '@/components/ImgUpload'
import { addDish, editDish, getCategoryList, queryDishById } from '@/api/dish'

export default function AddDishtype(){
 const nav=useNavigate();const [search]=useSearchParams();const id=search.get('id');const [form]=Form.useForm();const [cats,setCats]=useState<any[]>([]);const [saving,setSaving]=useState(false)
 useEffect(()=>{getCategoryList({type:1}).then(r=>r.data.code===1&&setCats(r.data.data||[]));if(id)queryDishById(id).then(r=>{if(r.data.code===1){const d=r.data.data;form.setFieldsValue({...d,status:String(d.status)==='1',flavors:(d.flavors||[]).map((f:any)=>({...f,value:Array.isArray(f.value)?f.value:JSON.parse(f.value||'[]')}))})}else message.error(r.data.msg)})},[id,form])
 const submit=async(stay=false)=>{const v=await form.validateFields();setSaving(true);try{const payload={...v,status:id?(v.status?1:0):0,flavors:(v.flavors||[]).map((f:any)=>({...f,value:JSON.stringify(f.value||[])})),...(id?{id}: {})};const r=id?await editDish(payload):await addDish(payload);if(r.data.code===1){message.success(id?'Item updated successfully.':'Item added successfully.');if(stay&&!id)form.resetFields();else nav('/dish')}else message.error(r.data.msg||r.data.desc)}finally{setSaving(false)}}
 return <div className="dashboard-container"><div className="content-card"><HeadLable title={id?'Edit Item':'Add Items'}/><Form form={form} layout="vertical" initialValues={{status:true,flavors:[]}} style={{maxWidth:700}}><Form.Item label="Item Name" name="name" rules={[{required:true,message:'Enter an item name'},{pattern:/^([A-Za-z0-9\u4e00-\u9fa5]){2,20}$/,message:'Use 2–20 letters, numbers, or Chinese characters'}]}><Input/></Form.Item><Form.Item label="Item Category" name="categoryId" rules={[{required:true,message:'Select an item category'}]}><Select options={cats.map(c=>({value:c.id,label:c.name}))}/></Form.Item><Form.Item label="Item Price" name="price" rules={[{required:true,message:'Enter an item price'},{pattern:/^([1-9]\d{0,5}|0)(\.\d{1,2})?$/,message:'Use no more than two decimal places'}]}><Input prefix="￥"/></Form.Item><Form.Item label="Item Code" name="code" rules={[{required:true,message:'Enter an item code'}]}><Input/></Form.Item><Form.Item label="Item Image" name="image" rules={[{required:true,message:'Upload an item image'}]}><ImgUpload/></Form.Item>
 <Form.List name="flavors">{(fields,{add,remove})=><><div style={{marginBottom:8}}>Flavor Options</div>{fields.map(f=><Space key={f.key} align="baseline" style={{display:'flex'}}><Form.Item name={[f.name,'name']} rules={[{required:true,message:'Enter a flavor name'}]}><Input placeholder="Flavor name, e.g. spice level"/></Form.Item><Form.Item name={[f.name,'value']} rules={[{required:true,message:'Add at least one flavor option'}]}><Select mode="tags" style={{width:360}} placeholder="Type an option and press Enter"/></Form.Item><MinusCircleOutlined onClick={()=>remove(f.name)}/></Space>)}<Button type="dashed" icon={<PlusOutlined/>} onClick={()=>add({name:'',value:[]})}>Add Flavor</Button></>}</Form.List>
 <Form.Item label="Description" name="description" style={{marginTop:20}}><Input.TextArea rows={3}/></Form.Item>{id&&<Form.Item label="Sale Status" name="status" valuePropName="checked"><Switch checkedChildren="On Sale" unCheckedChildren="Off Sale"/></Form.Item>}<Space><Button onClick={()=>nav('/dish')}>Cancel</Button><Button type="primary" loading={saving} onClick={()=>submit(false)}>Save</Button>{!id&&<Button loading={saving} onClick={()=>submit(true)}>Save & Add Another</Button>}</Space></Form></div></div>
}
