import { useCallback, useEffect, useState } from 'react'
import { Button, Image, Input, Modal, Pagination, Select, Space, Table, message } from 'antd'
import { PlusOutlined, SearchOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { deleteDish, dishCategoryList, dishStatusByStatus, getDishPage } from '@/api/dish'
import noImg from '@/assets/noImg.png'

export default function Dish(){
 const nav=useNavigate(); const [name,setName]=useState('');const [categoryId,setCategoryId]=useState<number>();const [status,setStatus]=useState<number>();const [cats,setCats]=useState<any[]>([]);const [rows,setRows]=useState<any[]>([]);const [selected,setSelected]=useState<React.Key[]>([]);const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(10);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(false)
 const load=useCallback(async()=>{setLoading(true);try{const r=await getDishPage({page,pageSize,name:name||undefined,categoryId:categoryId||undefined,status});if(r.data.code===1){setRows(r.data.data.records||[]);setTotal(Number(r.data.data.total||0))}else message.error(r.data.msg)}finally{setLoading(false)}},[page,pageSize,name,categoryId,status])
 useEffect(()=>{dishCategoryList({type:1}).then(r=>r.data.code===1&&setCats(r.data.data||[]))},[]);useEffect(()=>{load()},[load])
 const remove=(ids:string)=>Modal.confirm({title:'Confirm Delete',content:'This will permanently delete the item. Continue?',okText:'Delete',okButtonProps:{danger:true},onOk:async()=>{const r=await deleteDish(ids);if(r.data.code===1){message.success('Deleted successfully.');setSelected([]);load()}else message.error(r.data.msg)}})
 const toggle=(r:any)=>Modal.confirm({title:'Notice',content:`Confirm${r.status?'Off Sale':'On Sale'} this item?`,onOk:async()=>{const x=await dishStatusByStatus({id:r.id,status:r.status?0:1});if(x.data.code===1||x.status===200){message.success('Item status updated.');load()}else message.error(x.data.msg)}})
 return <div className="dashboard-container"><div className="content-card"><div className="tableBar"><span>Item Name:</span><Input value={name} allowClear placeholder="Enter Item Name" style={{width:180}} onChange={e=>setName(e.target.value)}/><span>Item Category:</span><Select value={categoryId} allowClear style={{width:160}} options={cats.map(c=>({value:c.id,label:c.name}))} onChange={setCategoryId}/><span>Sale Status:</span><Select value={status} allowClear style={{width:130}} options={[{value:0,label:'Off Sale'},{value:1,label:'On Sale'}]} onChange={setStatus}/><Button type="primary" icon={<SearchOutlined/>} onClick={()=>{setPage(1);load()}}>Search</Button><span className="spacer"/><Button danger disabled={!selected.length} onClick={()=>remove(selected.join(','))}>Delete Selected</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>nav('/dish/add')}>Add Item</Button></div>
 <Table rowKey="id" loading={loading} dataSource={rows} pagination={false} rowSelection={{selectedRowKeys:selected,onChange:setSelected}} columns={[{title:'Item Name',dataIndex:'name'},{title:'Image',dataIndex:'image',render:v=><Image width={80} height={40} style={{objectFit:'cover'}} src={v} fallback={noImg}/>},{title:'Item Category',dataIndex:'categoryName'},{title:'Price',dataIndex:'price',render:v=>`￥${Number(Number(v).toFixed(2))}`},{title:'Sale Status',dataIndex:'status',render:v=><span className={`tableColumn-status ${String(v)==='0'?'stop-use':''}`}>{String(v)==='0'?'Off Sale':'On Sale'}</span>},{title:'Last Updated',dataIndex:'updateTime'},{title:'Actions',width:230,render:(_,r:any)=><Space><Button type="link" onClick={()=>nav(`/dish/add?id=${r.id}`)}>Edit</Button><Button type="link" danger onClick={()=>remove(String(r.id))}>Delete</Button><Button type="link" onClick={()=>toggle(r)}>{r.status?'Off Sale':'On Sale'}</Button></Space>}]}/><div className="pageList"><Pagination current={page} pageSize={pageSize} total={total} showSizeChanger showQuickJumper showTotal={n=>`${n} total`} onChange={(p,s)=>{setPage(p);setPageSize(s)}}/></div></div></div>
}
