const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '../src')
const replacements = {
  '当前餐厅处于营业状态，自动接收任何订单，可点击打烊进入店铺打烊状态。': 'The restaurant is open and can receive orders. Select Closed to stop normal order intake.',
  '当前餐厅处于打烊状态，仅接受营业时间内的预定订单，可点击营业中手动恢复营业状态。': 'The restaurant is closed. Select Open to resume normal order intake.',
  '当前浏览器无法接收实时报警信息，请使用谷歌浏览器！': 'This browser cannot receive real-time order alerts. Please use Chrome.',
  '服务器错误，无法接收实时报警信息': 'Server error: real-time order alerts are unavailable.',
  '订单量较多，暂时无法接单': 'Order volume is too high',
  '菜品已销售完，暂时无法接单': 'Items are sold out',
  '餐厅已打烊，暂时无法接单': 'Restaurant is closed',
  '骑手不足无法配送': 'Not enough delivery drivers',
  '客户电话取消': 'Customer canceled by phone',
  '账号输入不符，必须为3-20个小写字母或数字': 'Use 3–20 lowercase letters or numbers',
  '菜品名称为2-20个中英文或数字字符': 'Use 2–20 letters, numbers, or Chinese characters',
  '套餐名称为2-20个中英文或数字字符': 'Use 2–20 letters, numbers, or Chinese characters',
  '分类名称长度为2-20个字符': 'Category name must be 2–20 characters',
  '分类名称仅包含中英文字符': 'Use letters or Chinese characters only',
  '此操作将永久删除该分类，是否继续?': 'This will permanently delete the category. Continue?',
  '此操作将永久删除该菜品，是否继续?': 'This will permanently delete the item. Continue?',
  '此操作将永久删除该套餐，是否继续?': 'This will permanently delete the combo. Continue?',
  '确认调整该账号的状态?': 'Change this account status?',
  '确认调整该分类的状态?': 'Change this category status?',
  '6 - 20位密码，数字或字母，区分大小写': '6–20 letters or numbers (case-sensitive)',
  '密码不一致，请重新输入密码': 'Passwords do not match',
  '您有1个订单待处理,': 'You have a new order: ',
  ',请及时接单': '. Please accept it promptly.',
  '保存并继续添加': 'Save & Add Another',
  'Sorry，木有找到您搜索的内容哦~': 'No matching results found.',
  '这里空空如也~': 'No data available.',
  '运营数据统计报表.xlsx': 'Operations-Report.xlsx',
  '苍穹外卖': 'Sky Take-Out',
  '营业状态设置': 'Business Status',
  '浏览器WebSocket已打开': 'WebSocket connected',
  'WebSocket已关闭': 'WebSocket closed',
  '修改员工信息': 'Edit Employee',
  '员工信息修改成功！': 'Employee updated successfully.',
  '员工添加成功！': 'Employee added successfully.',
  '账号状态更改成功！': 'Account status updated.',
  '分类状态更改成功！': 'Category status updated.',
  '菜品状态更改成功！': 'Item status updated.',
  '套餐状态更改成功！': 'Combo status updated.',
  '分类修改成功！': 'Category updated successfully.',
  '分类添加成功！': 'Category added successfully.',
  '菜品修改成功！': 'Item updated successfully.',
  '菜品添加成功！': 'Item added successfully.',
  '套餐修改成功！': 'Combo updated successfully.',
  '套餐添加成功！': 'Combo added successfully.',
  '密码修改成功': 'Password updated successfully.',
  '修改密码': 'Change Password',
  '退出登录': 'Sign Out',
  '营业中': 'Open',
  '打烊中': 'Closed',
  '待付款': 'Pending Payment',
  '待接单': 'Pending Acceptance',
  '待派送': 'Ready for Delivery',
  '派送中': 'Out for Delivery',
  '已完成': 'Completed',
  '已取消': 'Canceled',
  '全部订单': 'All Orders',
  '订单详情': 'Order Details',
  '拒绝订单': 'Reject Order',
  '取消订单': 'Cancel Order',
  '自定义原因': 'Other',
  '请选择拒绝原因': 'Select a rejection reason',
  '请选择取消原因': 'Select a cancellation reason',
  '请输入原因': 'Enter a reason',
  '操作成功': 'Operation completed.',
  '工作台': 'Dashboard',
  '数据统计': 'Analytics',
  '订单管理': 'Order Management',
  '套餐管理': 'Combo Management',
  '菜品管理': 'Item Management',
  '分类管理': 'Category Management',
  '员工管理': 'Employee Management',
  '添加菜品': 'Add Item',
  '修改菜品': 'Edit Item',
  '添加套餐': 'Add Combo',
  '修改套餐': 'Edit Combo',
  '添加员工': 'Add Employee',
  '营业额统计': 'Revenue',
  '用户统计': 'Customers',
  '订单统计': 'Orders',
  '销量排名 TOP10': 'Top 10 Items',
  '订单完成率': 'Completion Rate',
  '营业额': 'Revenue',
  '有效订单': 'Valid Orders',
  '平均客单价': 'Average Order Value',
  '新增用户': 'New Customers',
  '总用户': 'Total Customers',
  '订单数': 'Total Orders',
  '菜品总览': 'Item Overview',
  '套餐总览': 'Combo Overview',
  '已启售': 'On Sale',
  '已停售': 'Off Sale',
  '查看全部': 'View All',
  '新增菜品分类': 'Add Item Category',
  '新增套餐分类': 'Add Combo Category',
  '修改分类': 'Edit Category',
  '菜品分类': 'Item Category',
  '套餐分类': 'Combo Category',
  '分类名称': 'Category Name',
  '分类类型': 'Category Type',
  '操作时间': 'Last Updated',
  '最后操作时间': 'Last Updated',
  '员工姓名': 'Employee Name',
  '账号状态': 'Account Status',
  '手机号': 'Phone',
  '身份证号': 'ID Number',
  '性别': 'Gender',
  '账号': 'Username',
  '菜品名称': 'Item Name',
  '菜品价格': 'Item Price',
  '菜品编码': 'Item Code',
  '菜品图片': 'Item Image',
  '菜品描述': 'Description',
  '套餐名称': 'Combo Name',
  '套餐价格': 'Combo Price',
  '套餐编码': 'Combo Code',
  '套餐图片': 'Combo Image',
  '套餐描述': 'Description',
  '套餐菜品': 'Combo Items',
  '售卖状态': 'Sale Status',
  '实收金额': 'Amount Paid',
  '下单时间': 'Order Time',
  '订单状态': 'Order Status',
  '订单菜品': 'Order Items',
  '订单号': 'Order Number',
  '预计送达时间': 'Estimated Delivery',
  '支付方式': 'Payment Method',
  '微信支付': 'WeChat Pay',
  '支付宝支付': 'Alipay',
  '收货人': 'Recipient',
  '地址': 'Address',
  '备注': 'Notes',
  '数量': 'Quantity',
  '金额': 'Amount',
  '价格': 'Price',
  '份数': 'Quantity',
  '图片': 'Image',
  '售价': 'Price',
  '套餐价': 'Price',
  '状态': 'Status',
  '排序': 'Sort Order',
  '操作': 'Actions',
  '启售': 'On Sale',
  '停售': 'Off Sale',
  '启用': 'Enabled',
  '禁用': 'Disabled',
  '查询': 'Search',
  '批量删除': 'Delete Selected',
  '新建菜品': 'Add Item',
  '新建套餐': 'Add Combo',
  '添加口味': 'Add Flavor',
  '口味配置': 'Flavor Options',
  '口味名，如辣度': 'Flavor name, e.g. spice level',
  '输入选项后回车': 'Type an option and press Enter',
  '添加菜品': 'Add Items',
  '上传图片': 'Upload Image',
  '重新上传': 'Replace Image',
  '删除图片': 'Remove Image',
  '上传文件大小不能超过': 'File size cannot exceed ',
  '图片上传失败': 'Image upload failed',
  '返回首页': 'Back to Dashboard',
  '返回': 'Back',
  '登录中...': 'Signing in...',
  '登录': 'Sign In',
  '密码': 'Password',
  '请输入用户名': 'Enter your username',
  '请输入密码': 'Enter your password',
  '密码必须在6位以上': 'Password must contain at least 6 characters',
  '原始密码': 'Current Password',
  '新密码': 'New Password',
  '确认密码': 'Confirm Password',
  '请再次输入密码': 'Re-enter your password',
  '请输入': 'Enter a value',
  '取消': 'Cancel',
  '确定': 'Confirm',
  '保存': 'Save',
  '删除成功！': 'Deleted successfully.',
  '确认删除': 'Confirm Delete',
  '删除': 'Delete',
  '修改': 'Edit',
  '查看': 'View',
  '接单': 'Accept',
  '拒单': 'Reject',
  '派送': 'Start Delivery',
  '完成': 'Complete',
  '关闭': 'Close',
  '退款': 'Refunded',
  '提示': 'Notice',
  '错误': 'Error',
  '取 消': 'Cancel',
  '确 定': 'Confirm',
  '保 存': 'Save',
  '请求出错了：': 'Request failed: ',
  '请求错误': 'Request error',
  '请选择': 'Select',
  '请输入账号': 'Enter a username',
  '请输入员工姓名': 'Enter an employee name',
  '请输入手机号': 'Enter a phone number',
  '请输入正确的手机号': 'Enter a valid phone number',
  '请输入身份证号': 'Enter an ID number',
  '身份证号码不正确': 'Enter a valid ID number',
  '请输入菜品名称': 'Enter an item name',
  '请选择菜品分类': 'Select an item category',
  '请输入菜品价格': 'Enter an item price',
  '请输入菜品编码': 'Enter an item code',
  '菜品图片不能为空': 'Upload an item image',
  '请输入套餐名称': 'Enter a combo name',
  '请选择套餐分类': 'Select a combo category',
  '请输入套餐价格': 'Enter a combo price',
  '请输入套餐编码': 'Enter a combo code',
  '套餐图片不能为空': 'Upload a combo image',
  '套餐下菜品不能为空': 'Add at least one item to the combo',
  '价格最多保留两位小数': 'Use no more than two decimal places',
  '请输入口味名': 'Enter a flavor name',
  '请选择口味值': 'Add at least one flavor option',
  '分类名称不能为空': 'Enter a category name',
  '排序不能为空': 'Enter a sort order',
  '确认': 'Confirm',
  '女': 'Female',
  '男': 'Male',
  '近7日': 'Last 7 Days',
  '近30日': 'Last 30 Days',
  '本周': 'This Week',
  '本月': 'This Month',
  '数据导出': 'Export',
  '共 ': '',
  ' 条': ' total',
  '去处理': 'View Order',
  '催单': 'Order Reminder',
  '集团管理': 'Management',
  '用户名': 'Customer',
  '菜品': 'Item',
  '实收：': 'Amount Paid: ',
  '请填写': 'Enter ',
  '该菜品?': ' this item?',
  '该套餐?': ' this combo?',
  '拒绝': 'Reject',
  '原因': ' reason',
  '新增': 'Add ',
  '分类': ' Category',
  '菜品': 'Item',
  '套餐': 'Combo',
  '：': ':',
}

function walk(dir) {
  for (const name of fs.readdirSync(dir)) {
    const file = path.join(dir, name)
    const stat = fs.statSync(file)
    if (stat.isDirectory()) walk(file)
    else if (/\.(ts|tsx)$/.test(name)) {
      let text = fs.readFileSync(file, 'utf8')
      for (const [from, to] of Object.entries(replacements).sort((a, b) => b[0].length - a[0].length)) {
        text = text.split(from).join(to)
      }
      fs.writeFileSync(file, text)
    }
  }
}

walk(root)
